# Display
GAME_TITLE = "Generic Game"
FPS = 60

# Tile dimensions
TILE_HEIGHT = 48  # 32
TILE_WIDTH = 48
TILE_DIMENSION = (TILE_WIDTH, TILE_HEIGHT)

# Screen dimensions
SCREEN_COLUMNS = 20
SCREEN_ROWS = 10
SCREEN_WIDTH = SCREEN_COLUMNS * TILE_WIDTH
SCREEN_HEIGHT = SCREEN_ROWS * TILE_HEIGHT
SCREEN_DIMENSION = (SCREEN_WIDTH, SCREEN_HEIGHT)

# World dimensions
WORLD_COLUMNS = 35
WORLD_ROWS = 35
WORLD_WIDTH = WORLD_COLUMNS * TILE_WIDTH
WORLD_HEIGHT = WORLD_ROWS * TILE_HEIGHT
WORLD_DIMENSION = (WORLD_WIDTH, WORLD_HEIGHT)

# Colors
BG_COLOR = (0, 0, 0)  # Black
GRID_COLOR = (150, 150, 150)  # Grey
PLAYER_BG_COLOR = (0, 255, 0)  # Green
MONSTER_BG_COLOR = (255, 0, 0)  # Red